---
title: "Regression tree analysis"
author: Peter Kamerman 
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  md_document:
    variant: markdown_github
---

## Load packages and set chunk options
```{r miscellaneous}
# Load libraries
library(pander)
library(readr)
library(knitr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(grid)
library(scales)
library(cowplot)
library(party)

# Set knitr chunk options
opts_chunk$set(echo = FALSE,
               warning = FALSE,
               message = FALSE,
               cache = FALSE,
               fig.path = './figures/',
               fig.height = 11.69,
               fig.width = 8.27,
               dev = c('png', 'pdf'),
               cache.extra = rand_seed,
               tidy = TRUE, 
               tidy.opts = list(width.cutoff = 65))
```

## Import data
```{r import}
# Read csv
data <- read_csv("./data/random.forest.csv", col_names = T)
# Remove patient ID column
data <- data[2:14]
```

## Inspect and clean data
```{r clean}
# Inspect the data
head(data)
tail(data)
summary(data)
str(data)

# Convert data classes as required
data$Pain <- factor(data$Pain, 
                    levels = c(0,1), 
                    labels = c('No', 'Yes'))
data$Female <- factor(data$Female, 
                      levels = c(0,1), 
                      labels = c('Male', 'Female'))
data$Education <- factor(data$Education, 
                         levels = c(0,1,2,3), 
                         labels = c('None', 'Primary', 'Secondary', 'Tertiary'))
data$Employment <- factor(data$Employment, 
                          levels = c(0,1), 
                          labels = c('No', 'Yes'))
data$Worry.Money <- factor(data$Worry.Money, 
                           levels = c(0,1,2,3,4), 
                           labels = c('Not at all', 'Rarely', 'Sometimes', 'Often', 'Nearly all the time'), 
                           ordered = T)
data$Worry.Family <- factor(data$Worry.Family, 
                            levels = c(0,1,2,3,4), 
                            labels = c('Not at all', 'Rarely', 'Sometimes', 'Often', 'Nearly all the time'), 
                            ordered = T)
data$Worry.Food <- factor(data$Worry.Food, 
                          levels = c(0,1,2,3,4), 
                          labels = c('Not at all', 'Rarely', 'Sometimes', 'Often', 'Nearly all the time'), 
                          ordered = T)
data$Worry.Health <- factor(data$Worry.Health, 
                            levels = c(0,1,2,3,4), 
                            labels = c('Not at all', 'Rarely', 'Sometimes', 'Often', 'Nearly all the time'), 
                            ordered = T)

# Inspect the data
str(data)

# Remove incomplete cases
data.2 <- data[complete.cases(data), ]

# dim data
dim(data)
dim(data.2)
```

## Activity
### Random Forest
```{r activity.forest}
# Trial 1 (ntree = 500, mtry = 3, seed = 123)
## Set seed
seed.123  <-  123
set.seed(seed.123)
## Set parameters (ntree = 500, mtry = 3)
### 'mtry' estimated to be sqrt of variables 
active.controls.1 <- cforest_unbiased(ntree = 500, 
                                      mtry = 3)
## Forest
active.forest.1 <- cforest(Median.Activity~., 
                           data = data.2, 
                           controls = active.controls.1)
## Extract variable importance
active.varimp.1 <- varimp(active.forest.1, 
                          conditional = TRUE)
active.trial.1 <- active.varimp.1

# Trial 2 (ntree = 2000, mtry = 3, seed = 123)
set.seed(seed.123)
## Set parameters (ntree = 2000, mtry = 3) 
### 'mtry' estimated to be sqrt of variables
active.controls.2 <- cforest_unbiased(ntree = 2000, 
                                      mtry = 3)
## Forest
active.forest.2 <- cforest(Median.Activity~., 
                           data = data.2, 
                           controls = active.controls.2)
## Extract variable importance
active.varimp.2 <- varimp(active.forest.2, 
                          conditional = TRUE)
active.trial.2 <- active.varimp.2

# Trial 3 (ntree = 500, mtry = 3, seed = 345)
## Set seed
seed.345 <- 345
set.seed(seed.345)
## Set parameters (ntree = 500, mtry = 3)
### 'mtry' estimated to be sqrt of variables 
active.controls.3 <- cforest_unbiased(ntree = 500, 
                                      mtry = 3)
## Forest
active.forest.3 <- cforest(Median.Activity~., 
                           data = data.2, 
                           controls = active.controls.3)
## Extract variable importance
active.varimp.3 <- varimp(active.forest.3, 
                          conditional = TRUE)
active.trial.3 <- active.varimp.3

# Trial 4 (ntree = 2000, mtry = 3, seed = 345)
set.seed(seed.345)
## Set parameters (ntree = 2000, mtry = 3) 
### 'mtry' estimated to be sqrt of variables
active.controls.4 <- cforest_unbiased(ntree = 2000, 
                                      mtry = 3)
## Forest
active.forest.4 <- cforest(Median.Activity~., 
                           data = data.2, 
                           controls = active.controls.4)
## Extract variable importance
active.varimp.4 <- varimp(active.forest.4, 
                          conditional = TRUE)
active.trial.4 <- active.varimp.4

## make a dataframe (active.df) of variable importance models
active.df <- data.frame(ID = names(active.trial.1),
                      "Trial 1" = active.trial.1, 
                      "Trial 2" = active.trial.2, 
                      "Trial 3" = active.trial.3, 
                      "Trial 4" = active.trial.4)

## make a dataframe (active.df2) of control parameters
active.df2 <- data.frame(ID = c("Seed", "ntree", "mtry"), 
                       "Trial 1" = c(seed.123, 500, 3), 
                       "Trial 2" = c(seed.123, 2000, 3), 
                       "Trial 3" = c(seed.345, 500, 3), 
                       "Trial 4" = c(seed.345, 2000, 3))
# Plot data
active.plot <- active.df %>%
    tbl_df() %>%
    gather(key = trial,
           value = importance,
           Trial.1:Trial.4) %>%
    group_by(trial) %>%
    arrange(importance)

# create df with data to plot abs(min(variable_importance))
MinVarImp.active <- active.plot %>%
    group_by(trial) %>%
    summarise(minimum = abs(min(importance)))

# ggplot
gg.active <- ggplot(data = active.plot, 
                    aes(x = ID, 
                        y = importance,
                        fill = ID)) +
    geom_point(shape = 21, 
               size = 5, 
               colour = 'black') +
    facet_grid(trial~.) +
    geom_hline(data = MinVarImp.active, 
               aes(yintercept = minimum), 
               linetype = 2) +
    labs(y = 'Variable importance\n') +
    scale_fill_manual(values = c('#000000', '#999999', '#999999', '#999999', '#000000', '#999999', '#999999', '#999999', '#999999', '#000000', '#999999', '#999999')) +
    scale_y_continuous(limits = c(-0.05, 0.15), 
                       expand = c(0, 0.001)) +
    scale_x_discrete(limits = c('Worry.Money', 'Worry.Health', 'EQ5D.vas', 'BMI', 'Female', 'Education', 'Pain', 'Worry.Family', 'RS.Prop.Score', 'Employment', 'Worry.Food', 'Age'),
                     labels = c('Worries about money', 'Worries about health', 'Quality of life', 'Body mass index', 'Sex', 'Education', 'Pain', 'Worries about familiy', 'Resilience', 'Employment', 'Worries about food', 'Age')) +
    theme_cowplot() +
    theme(legend.position = 'none',
          panel.margin.y = unit(1.3, 'lines'),
          axis.title.x = element_blank(),
          axis.text.x = element_text(angle = 35, 
                                     hjust = 1, 
                                     size = 16),
          axis.text.y = element_text(size = 16),
          axis.title.y = element_text(size = 16))
gg.active

# Report random forest settings for each plot
c('Seed','Number of trees grown', 'Number of variables sampled') %>%
    data.frame(Variable = .) %>%
    tbl_df() %>%
    bind_cols(., active.df2) %>%
    select(Variable, Trial.1, Trial.2, Trial.3, Trial.4) %>%
    kable(., format = 'markdown', align = 'l', caption = 'Random forest condition settings', col.names = c('', 'Trial 1', 'Trial 2', 'Trial 3', 'Trial 4'))
```

## Pain
### Random Forest
```{r pain.forest}
# Trial 1 (ntree = 500, mtry = 3, seed = 123)
## Set seed
seed.123 <- 123
set.seed(seed.123)
## Set parameters (ntree = 500, mtry = 3)
### 'mtry' estimated to be sqrt of variables 
pain.controls.1 <- cforest_unbiased(ntree = 500, 
                                    mtry = 3)
## Forest
pain.forest.1 <- cforest(Pain~., 
                         data = data.2, 
                         controls = pain.controls.1)
## Extract variable importance
pain.varimp.1 <- varimp(pain.forest.1, 
                        conditional = TRUE)
pain.trial.1 <- pain.varimp.1

# Trial 2 (ntree = 2000, mtry = 3, seed = 123)
set.seed(seed.123)
## Set parameters (ntree = 2000, mtry = 3) 
### 'mtry' estimated to be sqrt of variables
pain.controls.2 <- cforest_unbiased(ntree = 2000, 
                                    mtry = 3)
## Forest
pain.forest.2 <- cforest(Pain~., 
                         data = data.2, 
                         controls = pain.controls.2)
## Extract variable importance
pain.varimp.2 <- varimp(pain.forest.2, 
                        conditional = TRUE)
pain.trial.2 <- pain.varimp.2

# Trial 3 (ntree = 500, mtry = 3, seed = 345)
## Set seed
seed.345 <- 345
set.seed(seed.345)
## Set parameters (ntree = 500, mtry = 3)
### 'mtry' estimated to be sqrt of variables 
pain.controls.3 <- cforest_unbiased(ntree = 500, 
                                    mtry = 3)
## Forest
pain.forest.3 <- cforest(Pain~., 
                         data = data.2, 
                         controls = pain.controls.3)
## Extract variable importance
pain.varimp.3 <- varimp(pain.forest.3, 
                        conditional = TRUE)
pain.trial.3 <- pain.varimp.3

# Trial 4 (ntree = 2000, mtry = 3, seed = 345)
set.seed(seed.345)
## Set parameters (ntree = 2000, mtry = 3) 
### 'mtry' estimated to be sqrt of variables
pain.controls.4 <- cforest_unbiased(ntree = 2000, 
                                    mtry = 3)
## Forest
pain.forest.4 <- cforest(Pain~., 
                         data = data.2, 
                         controls = pain.controls.4)
## Extract variable importance
pain.varimp.4 <- varimp(pain.forest.4, 
                        conditional = TRUE)
pain.trial.4 <- pain.varimp.4

## make a dataframe (active.df) of variable importance models
pain.df <- data.frame(ID = names(pain.trial.1),
                      "Trial 1" = pain.trial.1, 
                      "Trial 2" = pain.trial.2, 
                      "Trial 3" = pain.trial.3, 
                      "Trial 4" = pain.trial.4)

## make a dataframe (pain.df2) of control parameters
pain.df2 <- data.frame(ID = c("Seed", "ntree", "mtry"), 
                       "Trial 1" = c(seed.123, 500, 3), 
                       "Trial 2" = c(seed.123, 2000, 3), 
                       "Trial 3" = c(seed.345, 500, 3), 
                       "Trial 4" = c(seed.345, 2000, 3))
data
# Plot data
pain.plot <- pain.df %>%
    tbl_df() %>%
    gather(key = trial,
           value = importance,
           Trial.1:Trial.4) %>%
    group_by(trial) %>%
    arrange(importance)

# create df with data to plot abs(min(variable_importance))
MinVarImp.pain <- pain.plot %>%
    group_by(trial) %>%
    summarise(minimum = abs(min(importance)))

pain.plot
# ggplot
gg.pain <- ggplot(data = pain.plot, 
                    aes(x = ID, 
                        y = importance,
                        fill = ID)) +
    geom_point(shape = 21, 
               size = 5, 
               colour = 'black') +
    facet_grid(trial~.) +
    geom_hline(data = MinVarImp.pain, 
               aes(yintercept = minimum), 
               linetype = 2) +
    labs(y = 'Variable importance\n') +
    scale_fill_manual(values = c('#999999', '#999999', '#000000', '#999999', '#999999', '#999999', '#999999', '#999999', '#999999', '#999999', '#000000', '#000000')) +
    scale_y_continuous(limits = c(-0.05, 0.15), 
                       expand = c(0, 0.001)) +
    scale_x_discrete(limits = c('Median.Activity', 'Education', 'Age', 'Female', 'BMI', 'RS.Prop.Score', 'Employment', 'Worry.Family', 'Worry.Food', 'Worry.Health', 'Worry.Money', 'EQ5D.vas'),
                     labels = c('Activity', 'Education', 'Age', 'Sex', 'Body mass index', 'Resilience', 'Employment', 'Worries about family', 'Worries about food', 'Worries about health', 'Worries about money', 'Quality of life')) +
    theme_cowplot() +
    theme(legend.position = 'none',
          panel.margin.y = unit(1.3, 'lines'),
          axis.title.x = element_blank(),
          axis.text.x = element_text(angle = 35, 
                                     hjust = 1, 
                                     size = 16),
          axis.text.y = element_text(size = 16),
          axis.title.y = element_text(size = 16))
gg.pain

# Report random forest settings for each plot
c('Seed','Number of trees grown', 'Number of variables sampled') %>%
    data.frame(Variable = .) %>%
    tbl_df() %>%
    bind_cols(., pain.df2) %>%
    select(Variable, Trial.1, Trial.2, Trial.3, Trial.4) %>%
    kable(., format = 'markdown', align = 'l', caption = 'Random forest condition settings', col.names = c('', 'Trial 1', 'Trial 2', 'Trial 3', 'Trial 4'))
```
